### ISSUE TITLE
Problems when using jRuby 9.1.6.0

### ISSUE THREAD

**Issue by lortega** [rubysl/rubysl-open3#1]
I ran the tests with jRuby 9.1.6.0 and got these results:

```
➜  rubysl-open3 git:(2.0) mspec .
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0
jruby 9.1.6.0 (2.3.1) 2016-11-09 0150a76 Java HotSpot(TM) 64-Bit Server VM 25.101-b13 on 1.8.0_101-b13 +jit [darwin-x86_64]
...........F..

1)
Open3.popen3 executes a process with a pipe to read stderr FAILED
Expected "Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256M; support was removed in 8.0\nfoo"
to equal "foo"

/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/expectations/expectations.rb:15:in `fail_with'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/matchers/base.rb:9:in `=='
/Users/someuser/Workspace/OpenSource/rubysl-open3/spec/popen3_spec.rb:17:in `block in (root)'
org/jruby/RubyBasicObject.java:1689:in `instance_eval'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:69:in `protect'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/context.rb:179:in `block in protect'
org/jruby/RubyEnumerable.java:1586:in `all?'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/context.rb:179:in `protect'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/context.rb:208:in `block in process'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:239:in `block in repeat'
org/jruby/RubyFixnum.java:299:in `times'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:238:in `repeat'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/context.rb:200:in `block in process'
org/jruby/RubyArray.java:1734:in `each'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/context.rb:199:in `process'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:38:in `describe'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/object.rb:11:in `describe'
/Users/someuser/Workspace/OpenSource/rubysl-open3/spec/popen3_spec.rb:3:in `<main>'
org/jruby/RubyKernel.java:977:in `load'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:1:in `block in (root)'
org/jruby/RubyBasicObject.java:1689:in `instance_eval'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:57:in `files'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:69:in `block in protect'
org/jruby/RubyArray.java:1734:in `each'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:57:in `files'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:51:in `files'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/runner/mspec.rb:43:in `process'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/lib/mspec/commands/mspec-run.rb:94:in `run'
/Users/someuser/.rvm/gems/jruby-9.1.6.0/gems/mspec-1.9.1/bin/mspec-run:8:in `<main>'

Finished in 23.458000 seconds

11 files, 3 examples, 3 expectations, 1 failure, 0 errors
```

**Comment by brixen** [comment]
@lortega this failure doesn't have anything to do with the library. Your JRuby instance is writing unexpected text to stderr.

**Comment by lortega** [comment]
@brixen so, If you run the same tests on jruby you get the same tests passing?

**Comment by chuckremes** [comment]
@lortega No. JRuby is writing that JVM warning text to stderr when it shouldn't be. This exposes a problem in JRuby. JRuby should be suppressing those warnings when called via popen. For example, when called via popen then stdout, stdin, and stderr are probably NOT ttys. If those file descriptors are not a TTY (see `IO.tty?`) then the warning should not get written to stderr.

I suggest opening a bug with JRuby and using this as a reproduction of the error.
